export const elementIDs = [
	"compost-audio",
	"compost-audio-clip-editor",
	"compost-midi",
	"compost-device-selector",
	"compost-drawer",
	"compost-knob",
	"compost-slider",
	"compost-meter",
	"compost-number-box",
	"compost-button",
	"compost-select",
	"compost-piano",
	"compost-scope",
	"compost-waveform",
	"compost-midi-monitor",
	"compost-midi-mappings",
	"compost-clip-grid",
	"compost-envelope-editor",
	"compost-note-editor",
	"compost-timeline",
	"compost-window",
	"compost-popup",
];

const elementSummaries = {
	"compost-audio": "Starts, suspends, and resumes Web Audio.",
	"compost-audio-clip-editor": "Edits audio clip ranges and loops.",
	"compost-midi": "Selects MIDI inputs and outputs.",
	"compost-device-selector": "Edits audio and MIDI device settings.",
	"compost-drawer": "Opens and resizes an edge drawer.",
	"compost-knob": "Edits a continuous parameter with a knob.",
	"compost-slider": "Edits a continuous parameter with a slider.",
	"compost-meter": "Displays live peak, average, and held levels.",
	"compost-number-box": "Edits an exact numeric parameter value.",
	"compost-button": "Triggers actions and toggles parameters.",
	"compost-select": "Chooses a discrete parameter value.",
	"compost-piano": "Plays notes from pointer, touch, or keyboard input.",
	"compost-scope": "Draws a supplied waveform.",
	"compost-waveform": "Renders a supplied min/max waveform overview.",
	"compost-midi-monitor": "Displays recent MIDI messages.",
	"compost-midi-mappings": "Lists and edits MIDI CC mappings.",
	"compost-clip-grid": "Launches and edits clips across tracks and scenes.",
	"compost-envelope-editor": "Draws and edits a breakpoint envelope.",
	"compost-note-editor": "Edits MIDI notes, velocity, loops, and ranges.",
	"compost-timeline": "Arranges clips and automation across tracks.",
	"compost-window": "Moves and resizes a floating panel.",
	"compost-popup": "Opens a keyboard-accessible option menu.",
};

const elementExamples = elementIDs.map((id) => ({
	id,
	href: `./${id}/`,
	title: id,
	summary: elementSummaries[id],
}));

export const examples = [
	{
		id: "monosynth",
		href: "./monosynth/",
		title: "Mono Synth",
		summary: "Plays an editable monophonic synth patch.",
		components: [
			"compost-audio",
			"compost-button",
			"compost-drawer",
			"compost-envelope-editor",
			"compost-knob",
			"compost-meter",
			"compost-midi",
			"compost-midi-mappings",
			"compost-midi-monitor",
			"compost-note-editor",
			"compost-number-box",
			"compost-piano",
			"compost-scope",
			"compost-select",
			"compost-slider",
		],
		utilities: ["ParameterController", "MIDIMappings"],
		runtime: "JavaScript AudioWorklet.",
	},
	{
		id: "midi-controller",
		href: "./midi-controller/",
		title: "MIDI Controller",
		summary: "Output-only MIDI controller.",
		components: [
			"compost-midi",
			"compost-button",
			"compost-knob",
			"compost-piano",
		],
		utilities: ["MIDI helpers"],
		runtime: "Web MIDI output.",
	},
	...elementExamples,
	{
		id: "parameter-sync",
		href: "./parameter-sync/",
		title: "Parameter Sync",
		summary: "Keeps two controls synchronized with host state.",
		components: ["compost-knob", "compost-slider"],
		utilities: ["ParameterController"],
		runtime: "DOM only.",
	},
];

export function getExample(id) {
	return examples.find((example) => example.id === id);
}
