import "./example-page.js";

const EVENT_READOUT_IDS = new Set([
	"compost-audio",
	"compost-audio-clip-editor",
	"compost-button",
	"compost-clip-grid",
	"compost-device-selector",
	"compost-drawer",
	"compost-envelope-editor",
	"compost-knob",
	"compost-midi",
	"compost-midi-mappings",
	"compost-note-editor",
	"compost-number-box",
	"compost-piano",
	"compost-popup",
	"compost-select",
	"compost-slider",
	"compost-timeline",
	"compost-window",
]);

const EVENT_TYPES = [
	"button-trigger",
	"parameter-begin",
	"parameter-edit",
	"parameter-end",
	"input",
	"change",
	"toggle",
	"drawer-resize",
	"window-open",
	"window-close",
	"window-move",
	"window-resize",
	"window-focus",
	"popup-open",
	"popup-close",
	"popup-select",
	"device-settings-refresh",
	"device-settings-input",
	"midi-ready",
	"midi-devices-changed",
	"midi-input-selected",
	"midi-output-selected",
	"midi-message",
	"midi-map-mode-change",
	"audio-started",
	"audio-resumed",
	"audio-suspended",
	"audio-stopped",
	"audio-state-change",
	"audio-error",
	"note-down",
	"note-up",
	"scope-frame",
	"clip-launch",
	"clip-stop",
	"clip-record",
	"clips-select",
	"clips-copy",
	"clips-paste",
	"clips-delete",
	"clips-duplicate",
	"clips-move",
	"clips-drag-start",
	"clips-drag-end",
	"clip-open",
	"clip-context",
	"clip-rename",
	"clip-delete",
	"clip-duplicate",
	"clip-trim-input",
	"clip-trim",
	"clip-split",
	"clip-join",
	"envelope-input",
	"envelope-change",
	"envelope-context",
	"envelope-selection",
	"notes-change",
	"note-quantize",
	"loop-input",
	"loop-change",
	"loop-toggle",
	"range-input",
	"range-change",
	"audio-file-drop",
	"selection-change",
	"note-preview",
	"note-preview-end",
	"note-context",
	"seek",
	"time-select-input",
	"time-select",
	"time-delete",
	"time-insert",
	"time-duplicate",
	"time-move-input",
	"time-move",
	"locator-jump",
	"locator-move",
	"locator-create",
	"locator-rename",
	"locator-delete",
	"locator-context",
	"locator-prev",
	"locator-next",
	"lane-pick",
	"lane-move",
	"lane-resize",
	"lanes-resize",
	"lane-rename",
	"lane-context",
	"lane-header-context",
	"lane-create",
	"lanes-context",
	"lanes-create",
	"ruler-context",
	"timeline-context",
	"automation-input",
	"automation-change",
	"automation-context",
	"draw-toggle",
	"fit-request",
	"view-change",
];

/** Attaches the event readout and returns the section for page-owned wiring. */
export async function elementDemo(
	id,
	{ output = EVENT_READOUT_IDS.has(id) } = {},
) {
	await import(`../../src/components/${id}.js`);
	await customElements.whenDefined(id);
	const s = document.querySelector("section.plain");
	const elements = s.querySelectorAll(id);
	const out = s.querySelector("output");
	if (output && out && elements.length) {
		for (const element of elements) {
			for (const type of EVENT_TYPES) {
				element.addEventListener(type, (event) => {
					const payload = event.detail ?? event.target.value;
					if (payload === undefined) return;
					out.textContent = `last event: ${type} ${JSON.stringify(payload)}`;
				});
			}
		}
	} else if (out) out.remove();
	return { s };
}
